services:
  backend:
    build:
      context: ./backend
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_WS_URL: ${VITE_WS_URL}
    env_file: .env
    ports:
      - "80:80"
    restart: always
